### ISSUE TITLE
[View] Improved the cutouts plot

### ISSUE THREAD

**Issue by FusRoman** [astrolabsoftware/fink-science-portal#117]
The actual ploting system of cutouts is not accurate. It produce a large contrast on the image and we cannot clearly distinguished the objects. 
example 1: http://134.158.75.151:24000/ZTF21aaowhdb
example 2: http://134.158.75.151:24000/ZTF21aaowgtq

**Comment by JulienPeloton** [comment]
Done in #118 -- thanks @FusRoman !
