### ISSUE TITLE
[Cutouts] New API service dedicated to cutouts only

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science-portal#122]
Recent PR (#120 ) enables downloading cutouts as 2D array with alert data -- but ideally we would like to have a dedicated service to download cutouts for immediate inspection. The query will require the following parameters:

- `candid` (or last alert given `objectId`)
- `type` (`Science`, `Template`, or `Difference`)
- `format` (PNG, or JPEG)

Something else? @karpov-sv

**Comment by karpov-sv** [comment]
I'd also add the following parameters:
- cmap (matplotlib colormap)
- min_cut / max_cut (percentiles for min/max values, to be used like `vmin,vmax = np.percentile(data, [min_cut, max_cut])`, and then passing them to `imshow`. Default values should be like [0.5, 99.5], which is sensible for most cases
- stretch (linear / log / asinh / sqrt, for different flux stretching options, probably to be passed to [astropy simple_norm or so](https://docs.astropy.org/en/stable/visualization/normalization.html))

Also, would be nice to have FITS as a possible format too.

**Comment by JulienPeloton** [comment]
Thanks, it is noted!

**Comment by JulienPeloton** [comment]
@karpov-sv there is a new service to download cutouts (PNG, FITS, or just data array) --> #130

Let me know if this is useful!

**Comment by JulienPeloton** [comment]
Done in #130
