### ISSUE TITLE
New features: magnitude increase rate per day and colour evolution per day 

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science-portal#15]
New features: magnitude increase rate per day and colour evolution per day (e.g. g-r) for the first 14 days of a new detection. More specifically between the last two measurements and the first and last measurement available.     
Corroborated by https://arxiv.org/pdf/2010.09724.pdf Figure 7!

**Comment by JulienPeloton** [comment]
Partially answered in #79 . Still remains: add a new plot in the SN tab with (r-g) evolution

**Comment by JulienPeloton** [comment]
We also need to improve the performance of the code, see #99

**Comment by JulienPeloton** [comment]
Now, thanks the @anaismoller, it needs to be `g-r` :D

**Comment by JulienPeloton** [comment]
Also - we would like to have it per band. This means rewriting the code per band, and updating the API documentation

**Comment by anaismoller** [comment]
for colour we need only `g-r `  and `deltag-r = (g-r)last - (g-r)_last-1` but this could be tricky with NaNs. Thus only `g-r` is ok for the time being. 
However rate of change only per band in magnitude `delta_r = r_last - r_last-1` and `delta_r = r_last - g_last-1`

**Comment by JulienPeloton** [comment]
Perfect, this is noted!

**Comment by JulienPeloton** [comment]
Done in #139
