### ISSUE TITLE
Limit the number of times an object is listed in class search

### ISSUE THREAD

**Issue by MatSmithAstro** [astrolabsoftware/fink-science-portal#311]
Hi Julien and co, 
I've been playing around with the class search option today: in particular the 'early SNeIa' and 'supernova candidates' list. 
These are really useful methods to quickly find interesting objects, and I can see myself using them regularly, but it seems that the output lists often list the same candidate multiple times. (For example ZTF19aatvkrn is currently the top two entries on the KN list). 
It would be great if these lists could only list each object once (i.e. a unique list). 
As an extension, can the search results also include the date of first detection or first time they passed the given criteria? It would really help filter out young and old SNe :-). 
Thanks! 
Mat

**Comment by JulienPeloton** [comment]
Hi Mat -- thanks for the feedback!

On the first point, I can add an option to show only the latest alert of an object if multiple. While this is an easy extension on the API, I need to think a bit about how to incorporate this on the web portal (typical UX nightmare...). Concerning the extension, it can be added indeed! I will keep you in touch when these will be available.

**Comment by JulienPeloton** [comment]
Hi Matt, 

see the PR #316 -- I think it brings solution to your requests. I will deploy it within the next couple of days. Your feedback will be appreciated :-)

**Comment by MatSmithAstro** [comment]
Love it! Will test it out over the next couple of days and let you know if I run into any issues :-).
