### ISSUE TITLE
aesthetic of the Supernova tab

### ISSUE THREAD

**Issue by emilleishida** [astrolabsoftware/fink-science-portal#33]
- in the legend below the probability score plot which says `Random Forest` should be  `Early SN score` (to be more homogeneous with the other 2 labels). 

- it would be nice to add more vertical space between the plots and between plots and axis labels,  to avoid lines on top of each other.

**Comment by emilleishida** [comment]
I put some marks in red where I think more space would be welcome.

![ubuntu_20 04 1_Chrome_87 0 4280 66_23inch_summary](https://user-images.githubusercontent.com/8313530/100339569-5035a100-2fda-11eb-98c6-45ff67dfde4f.png)

![ubuntu_20 04 1_Chrome_87 0 4280 66_23inch_supernovae](https://user-images.githubusercontent.com/8313530/100339605-5af03600-2fda-11eb-8fb6-9bfbcc73d806.png)

**Comment by JulienPeloton** [comment]
Layout updated (see #84)
