### ISSUE TITLE
reset bottom and not found message

### ISSUE THREAD

**Issue by emilleishida** [astrolabsoftware/fink-science-portal#36]
- whenever a give search does not find anything there should be a message: "nothing found"

- It would be nice to add a reset bottom to the search page and a message so the user is informed on the need to re-initiate after a search returning no alerts.

**Comment by JulienPeloton** [comment]
Thanks @emilleishida ! The first point has been added (see https://github.com/astrolabsoftware/fink-science-portal/pull/38). The second point will come later.

**Comment by JulienPeloton** [comment]
Reset button added! See #39 (and already online in the new version of the Portal)
