### ISSUE TITLE
Coordinates representation in alert Summary

### ISSUE THREAD

**Issue by pruzhinskaya** [astrolabsoftware/fink-science-portal#366]
For what does "ECL" stand here? The shown coordinates are equatorial but "ECL" sounds like ecliptic.
And the icon to copy the coordinates overlays on coordinates in Firefox 104.0.1.

https://fink-portal.org/ZTF20acxidhl

<img width="209" alt="изображение" src="https://user-images.githubusercontent.com/16917953/195635732-fb17b883-4439-4095-b5a7-c0591349f281.png">

**Comment by JulienPeloton** [comment]
> For what does "ECL" stand here? The shown coordinates are equatorial but "ECL" sounds like ecliptic.

You are absolutely right, thanks @pruzhinskaya ! ECL means ecliptic, but I meant equatorial. For my excuse, I was in a solar system rush... and did not pay attention to what I was writing T_T 
I will fix it.

>  And the icon to copy the coordinates overlays on coordinates in Firefox 104.0.1.

I do not think this a problem of browser, but rather screen resolution. Could you tell me which resolution you are using?

**Comment by pruzhinskaya** [comment]
👍
2560 x 1600 (MacBook Pro Retina 13”)

**Comment by JulienPeloton** [comment]
Ah -- Mac 13'', so even if they claim a native resolution of 2560 x 1600, the "apparent" resolution is only 1280 x 800. I could reproduce it:

![Screenshot from 2022-10-14 15-59-31](https://user-images.githubusercontent.com/20426972/195866680-5ef7dc89-bda0-48bf-bc87-2295b834c4de.png)

I will inspect what I can do.

**Comment by JulienPeloton** [comment]
The problem with Mac is the retina technology... For example, on my HP 13'' with 1920 x 1080 resolution (no change as retina does), this is what I see

![Screenshot from 2022-10-14 16-19-34](https://user-images.githubusercontent.com/20426972/195869977-1e801064-5056-42dc-9536-1d095918398d.png)

**Comment by JulienPeloton** [comment]
Fixed in #367
