### ISSUE TITLE
display alert classes by highest probability 

### ISSUE THREAD

**Issue by emilleishida** [astrolabsoftware/fink-science-portal#37]
In the explorer page, whenever someone chooses one of the classes in the drop down menu the list should show alerts in decreasing order of probability. 

In this case the user would see the most probable candidates first, and build confidence/intuition for subsequent searches.

**Comment by JulienPeloton** [comment]
The problem is that there is no unique single score to sort against. For example, the Early SN candidates are identified using:

```python
# SNN SN Ia
snn1 = snn_snia_vs_nonia.astype(float) > 0.5

# SNN SNe
snn2 = snn_sn_vs_all.astype(float) > 0.5

# Random forest
active_learn = rfscore.astype(float) > 0.5

# number of ZTF trigger @ 3 sigma
low_ndethist = ndethist.astype(int) < 400
early_ndethist = ndethist.astype(int) <= 20

# Real bogus
high_drb = drb.astype(float) > 0.5

# sextractor
high_classtar = classtar.astype(float) > 0.4

# SIMBAD
list_simbad_galaxies = [
    "galaxy",
    "Galaxy",
    "EmG",
    "Seyfert",
    "Seyfert_1",
    "Seyfert_2",
    "BlueCompG",
    "StarburstG",
    "LSB_G",
    "HII_G",
    "High_z_G",
    "GinPair",
    "GinGroup",
    "BClG",
    "GinCl",
    "PartofG",
]
keep_cds = \
    ["Unknown", "Candidate_SN*", "SN", "Transient"] + list_simbad_galaxies

# SN candidate filter
f_sn = (snn1 | snn2) & cdsxmatch.isin(keep_cds) & low_ndethist & high_drb & high_classtar

# Early SN candidate filter
f_sn_early = early_ndethist & active_learn & f_sn
```

So, in this case, we would need at least the score of the two SuperNNova module, and the score from the Random Forest. Any ideas on how to sort the results?

**Comment by emilleishida** [comment]
I would use the Random Forest score as a way of sorting for display. It is the one which is measuring Early SNe, the other ones can be high even if the supernova is already in the declining phase.

**Comment by JulienPeloton** [comment]
alright!

**Comment by JulienPeloton** [comment]
according to #73, now you can add extra columns (e.g. `rfscore`), and sort against it. Let me know if that solves this issue.
