### ISSUE TITLE
selecting data in 1passband is not satisfactory

### ISSUE THREAD

**Issue by anastasiabaluta** [astrolabsoftware/fink-science-portal#443]
On light curves choosing to study data from just 1 passband and clicking to hide data in another passband in the right upper corner, one can still see the limits and errors (represented in triangles) in the "hidden" passband on the figure. That can be quite confusing and is not convenient at all

Also, it would be useful to be able to turn off the "triangles" at all

**Comment by JulienPeloton** [comment]
Hi @anastasiabaluta -- thank you for your feedback! 

I agree with you, the current display is not convenient. I will try to see how to fix this.

**Comment by JulienPeloton** [comment]
Hi @anastasiabaluta -- I shipped a fix, let me know if this works for you!
