### ISSUE TITLE
data from specipic points on lightcurve can't be copied

### ISSUE THREAD

**Issue by anastasiabaluta** [astrolabsoftware/fink-science-portal#449]
There's a problem with copying data (e.g. magnitude, date, mjd) of each specific point on a lightcurve -- it can't be done, but sometimes it's needed. Might be helpful when you need to look the information up in some other resources

**Comment by JulienPeloton** [comment]
Hi @anastasiabaluta -- yes this is annoying to not be able to interact with the hover information! Unfortunately, this is not possible to keep the hover information persistent in Plotly python (see e.g. https://github.com/plotly/plotly.js/issues/998 -- the issue is broader, but related to).
