### ISSUE TITLE
cross-match with VSX 

### ISSUE THREAD

**Issue by pruzhinskaya** [astrolabsoftware/fink-science-portal#454]
Consider to add a link to AAVSO VSX in neighbourhood. They have more than 2 millions of variable stars.
https://www.aavso.org/vsx/index.php

**Comment by JulienPeloton** [comment]
Thanks @pruzhinskaya for the feedback -- but they do not seem to allow URL query (query by position from URL) as the other. Do you have an example?

**Comment by JulienPeloton** [comment]
Ah nevermind -- I found a way in this thread https://www.aavso.org/direct-web-query-vsxvsp

I will implement it then!

**Comment by pruzhinskaya** [comment]
For SNAD Viewer the data have been taken from VizieR: http://vizier.cds.unistra.fr/viz-bin/VizieR?-source=B%2Fvsx
