### ISSUE TITLE
Data transfer error ELASTICC v2

### ISSUE THREAD

**Issue by erusseil** [astrolabsoftware/fink-science-portal#487]
Crash when using data transfer for ELAsTiCC v2.
Bug reproduced on two separate computers. 

fink-client==6.0 (bug also exists in 5.0)
python==3.9.14
fastavro==1.6.0

I join screenshots of the error and the data transfer query
![Screenshot from 2023-07-25 16-11-14](https://github.com/astrolabsoftware/fink-client/assets/79919110/feb46e61-4b62-4a19-a998-03a812d3a0e8)
![Screenshot from 2023-07-25 16-10-45](https://github.com/astrolabsoftware/fink-client/assets/79919110/92a50524-e1ea-42d0-b7b6-372fb50d251c)

**Comment by JulienPeloton** [comment]
@bregeon @erusseil I've transfered this issue in the science portal (where the bug originates from). 
The problem has been fixed (multiple cast forgotten when generating the schema), and the fix has been deployed!
