### ISSUE TITLE
[Portal] Add option for coordinates in hours

### ISSUE THREAD

**Issue by anaismoller** [astrolabsoftware/fink-science-portal#505]
Add coordinates in hours for radio people and some interfaces.

Thanks!

Anais

**Comment by JulienPeloton** [comment]
Thanks for the feedback! In what format they want the coordinates? Do you mean hh:mm:ss dd:mm:ss? And where this should be displayed? In the coordinates dropdown in the object page, or they needed it elsewhere?

**Comment by anaismoller** [comment]
Thanks Julien, 
Indeed hh:mm:ss dd:mm:ss
Coordinate dropout menu is good. So we can copy paste it easily if needed!

**Comment by JulienPeloton** [comment]
Done! Now you have:

![Screenshot from 2023-10-05 09-49-02](https://github.com/astrolabsoftware/fink-science-portal/assets/20426972/a0607512-767c-4ebe-9f93-9a919e1d8460)
