### ISSUE TITLE
Badges for card view and object view

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science-portal#562]
The badges displayed for the card view:

https://github.com/astrolabsoftware/fink-science-portal/blob/c4d3a88c549466e870466c62d8a0f036330b540b/apps/cards.py#L1101

are often a subset of all the badges displayed for an object: 

https://github.com/astrolabsoftware/fink-science-portal/blob/c4d3a88c549466e870466c62d8a0f036330b540b/apps/cards.py#L906

I think we should centralise the badges computation, so that it can be called uniformly on various components.

**Comment by karpov-sv** [comment]
I cannot see how they may be easily combined, as the badges on summary page are extracted from the whole set of alerts for the object, and plus separate TNS call etc. That is the reason of this card being so slow to render (it often appears last when the page is loaded).

On the card view of search results you have just single - latest - alert (and e.g. for conesearch it is also significantly truncated), and no time for extra database calls. So we may extract only so much information here.
However I agree that the code for actual badge construction should be generalized into some utility function, to ease styling changes if needed

**Comment by JulienPeloton** [comment]
>  However I agree that the code for actual badge construction should be generalized into some utility function, to ease styling changes if needed

Actually my need was to expand the list of badges in the card view. I originally wanted to add the TNS badge -- and hopefully this should not add too much overheads. If we reformat the code to have a badge builder function, it will be easy to append the list of wanted badges in one place or another.

**Comment by karpov-sv** [comment]
Ok, I will do it. How you plan to get TNS information without overhead?..

**Comment by JulienPeloton** [comment]
Hum, I agree I timed the overhead, and currently this is about 0.81 +/- 0.06 sec/object. I will provide a faster way!

**Comment by karpov-sv** [comment]
Maybe some bulk request with all object names simultaneously would be faster?.. Especially if it may be converted into single DB scan, and not a loop as we did for comma-separated object names in object endpoint?..

**Comment by JulienPeloton** [comment]
I tried with a bulk request, but the gain is marginal (~20%). Actually the bottleneck is at the DB level because of the way the table is indexed (search based on ZTF objectId implies a `substring` strategy at the level of HBase key). I might have to redesign the table key the other way around as it seems we need more reverse search (ZTF -> TNS info) rather than direct search (TNS name -> ZTF) for intensive searches.

**Comment by karpov-sv** [comment]
Well, the amount of data is small so why don't have both?..

Alternatively, it might be a good reason to maybe start looking into SQL layer on top of HBase (Phoenix, IIRC) - Julius said he even already tried or maybe installed it on the database. It allows indexing non-key columns, so might be a good way to speed up such two-way searches.

**Comment by karpov-sv** [comment]
Should be mostly fixed in #572
