### ISSUE TITLE
NameError: name 'requests' is not defined

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science-portal#584]
The Data Transfer service does not work because there is missing import in `assets/spark_*.py` (a hot fix has been shipped in the main server in the meantime).

**Comment by karpov-sv** [comment]
That's strange, it is there on master branch
https://github.com/astrolabsoftware/fink-science-portal/blob/33809b9993e06eb8009db48a68e2e10d835907bd/assets/spark_ztf_transfer.py#L45
https://github.com/astrolabsoftware/fink-science-portal/blob/33809b9993e06eb8009db48a68e2e10d835907bd/assets/spark_elasticc_transfer.py#L40

**Comment by JulienPeloton** [comment]
Sorry wrong file -- the bug appears in `apps/query_cluster.py`, where `requests` is need e.g. line 561 when querying the log information.

**Comment by karpov-sv** [comment]
Yes, then that's my mistake... Should I directly push the hotfix, or you will do it from production server?

**Comment by JulienPeloton** [comment]
I will open a proper PR -- in the meantime I updated the file on the production server :-)
