### ISSUE TITLE
Search sensetive to register

### ISSUE THREAD

**Issue by pruzhinskaya** [astrolabsoftware/fink-science-portal#592]
<img width="302" alt="image" src="https://github.com/astrolabsoftware/fink-science-portal/assets/16917953/4560f1ec-e8bd-40ac-9a8e-758f8c4c368d">

**Comment by JulienPeloton** [comment]
Thanks for reporting! Actually the search is case insensitive for astronomical names, but case sensitive for ZTF object names. Let's see if that can be fixed easily.

**Comment by JulienPeloton** [comment]
A fix has been deployed (#593 )
