### ISSUE TITLE
Aladin Map default HiPS plane

### ISSUE THREAD

**Issue by pruzhinskaya** [astrolabsoftware/fink-science-portal#599]
Can we put back PS1 color map by default?

**Comment by JulienPeloton** [comment]
I do not what default you are referring as to. Before (when we were using Aladin Lite v2), we were using [color-z-zg-g/](https://alasky.cds.unistra.fr/Pan-STARRS/DR1/color-z-zg-g/), and now (Aladin v3), we are using [color-i-r-g/](https://alasky.cds.unistra.fr/Pan-STARRS/DR1/color-i-r-g/). I'm not an expert, but I have the impression the combination `i-r-g` was a better choice.

**Comment by karpov-sv** [comment]
I agree that three-color one has more information and (seemingly) less artifacts, but the visual scaling is indeed different, so the background is often too "colorful".
Maybe the default parameters for scaling/brightness/contrast may be slightly adjusted - I hope Aladin exposes them as variables too, not just as buttons inside the widge.

**Comment by pruzhinskaya** [comment]
Yes, I meant 2-colour map. With 3 colours it is too "colourful" and (at least for me) more difficult to look at.

**Comment by JulienPeloton** [comment]
ok -- i will revert to 2 colors unless @karpov-sv has a better idea to keep 3 colors while having a better display.

**Comment by karpov-sv** [comment]
I tried adjusting the gamma and color saturation using the code below (just to keep it somewhere - the same may be done interactively)
```diff
+    // Adjust the gamma and saturation of survey plane
+    aladin.getBaseImageLayer().setGamma(1.3);
+    aladin.getBaseImageLayer().setSaturation(-0.2);
```
but the result still was not satisfactory according to @pruzhinskaya. I have no strong preference here myself,  so agree to reverting it.

**Comment by JulienPeloton** [comment]
OK, I will make the change to 2 colors.
