### ISSUE TITLE
Accessing ssoft

### ISSUE THREAD

**Issue by jrob93** [astrolabsoftware/fink-science-portal#610]
Hi all,

I was just trying to access the ssoft table following the instructions at https://fink-portal.org/api. Specifically I was trying to get the whole table using
```
import io
import requests
import pandas as pd

r = requests.post(
  'https://fink-portal.org/api/v1/ssoft',
  json={
    'output-format': 'parquet'
  }
)

# Format output in a DataFrame
pdf = pd.read_parquet(io.BytesIO(r.content))
```
However I was getting a load of messages like `Corrupted thrift data at  129 :  14 0` which ended with an error: `TypeError: 'NoneType' object is not iterable`

**Comment by JulienPeloton** [comment]
Hi @jrob93 -- thanks for reporting! Indeed, I confirm there was a problem in computing the version `2024.04`. I'm on it, and in the meantime, you should be able to access the previous version from last month (`version: 2024.03`).

**Comment by jrob93** [comment]
Cool, no problem and thank you!

**Comment by JulienPeloton** [comment]
Data has been uploaded correctly -- and you should be able to access the latest version `2024.04`. Let me know if the problem persists.

**Comment by jrob93** [comment]
I can confirm that it's working now, cheers!
