### ISSUE TITLE
Retrieve object data tutorial is broken

### ISSUE THREAD

**Issue by emilleishida** [astrolabsoftware/fink-science-portal#630]
The example of plotting upper limits requires a key that is not available when retrieving data from the API

maskValid = pdf['d:tag'] == 'valid'

**Comment by JulienPeloton** [comment]
Thanks for reporting! Which tutorial are you talking about?

**Comment by emilleishida** [comment]
"Retrieve object data"

**Comment by JulienPeloton** [comment]
For future reference -- the option `"withupperlim": True` is needed to access the `d:tag` field :-)
