### ISSUE TITLE
Data Transfer: no error message when sending bad request

### ISSUE THREAD

**Issue by anaismoller** [astrolabsoftware/fink-science-portal#641]
Is it possible to have an error message when schema is wrong?

E.g. when requesting : jd - jd_first_real_det<10; indstead of candidate.jd - jd_first_real_det<10;

Topic: ftransfer_ztf_2024-07-22_204868

Only produces
24/07/22 14:41:51 -Livy- Generating data paths...

and no error message given

Thanks!

**Comment by JulienPeloton** [comment]
Thanks for reporting! This has been fixed and deployed with the PR https://github.com/astrolabsoftware/fink-science-portal/pull/642
