### ISSUE TITLE
Coordinate search format

### ISSUE THREAD

**Issue by anaismoller** [astrolabsoftware/fink-science-portal#648]
Conesearch format not supporting two points as shown in help bar. need to put spaces instead
e.g. 18 45 05.2 -63 57 47.4 r=10 

To reproduce enter:
18:45:05.2 -63:57:47.4 r=10   

  Thanks!

**Comment by JulienPeloton** [comment]
Hum, this sounds a bug! Thanks for reporting.

**Comment by JulienPeloton** [comment]
Although note that specifying `RA=` and `DEC=` works in that case

![Screenshot from 2024-09-04 07-54-03](https://github.com/user-attachments/assets/59bb2dc3-c0ce-47e2-97bd-3e4eb91a5817)

**Comment by anaismoller** [comment]
but with degrees we don't need RA, DEC. A bug or a feature ? ;)

**Comment by JulienPeloton** [comment]
The issue has been solved (#649 ). Let me know if you see more problems.
