### ISSUE TITLE
Cutouts: why are they zoomed on opening?

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science-portal#696]
When opening a new object page, the cutouts are often automatically zoomed (js code)... This might be mitigated by specifying `range=[min, max]` in the `axis_template` definition.

**Comment by JulienPeloton** [comment]
@karpov-sv -- any ideas? It is definitely happening in one of the clientside callbacks [linked_zoom_plots_xaxis_js](https://github.com/astrolabsoftware/fink-science-portal/blob/36211dcb8bbab6fbc622e56c77bf740cb19bbeec/apps/plotting.py#L1983C1-L1983C27) or [zoom_cutouts_js](https://github.com/astrolabsoftware/fink-science-portal/blob/36211dcb8bbab6fbc622e56c77bf740cb19bbeec/apps/plotting.py#L2371C1-L2371C16) -- but I cannot find what is wrong there... 

Tips: if you want to test locally on your computer, just checkout the branch [issue/689/noapi](https://github.com/astrolabsoftware/fink-science-portal/tree/issue/689/noapi) -- it is still WIP, but you can already deploy the code locally as I externalise the API part:

```bash
pip install -r requirements.txt
python index.py
# go to localhost:24000
```

**Comment by karpov-sv** [comment]
Yes, I remember this thing, I tried to track it down back then... It is due to some race conditions in events related to zooming, I was unable to easily fix it. 
Will try to look at it again

**Comment by JulienPeloton** [comment]
Ah -- I think I got it. Inspecting `relayout_data` more closely, it was in the form of e.g. `[{autorange: true}, undefined, undefined]` when all components did not have the time to initialise properly -- and `[{autorange: true}, {autorange: true}, {autorange: true}]` otherwise. So checking for `undefined` avoids the problem.
